<font color='green'>
Pip install is the command you use to install Python packages with the help of a tool called Pip package manager.
<br><br>Installing LangChain package along with langchain-openai, new update from langchain team
</font>

In [1]:
#!pip install langchain==0.1.4
#!pip install langchain-openai==0.0.5

<font color='green'>
Installing Openai package, which includes the classes that we can use to communicate with Openai services
<font>

In [2]:
#!pip install openai==1.10.0

## Let's use OpenAI

<font color='green'>
Imports the Python built-in module called "os."
<br>This module provides a way to interact with the operating system, such as accessing environment variables, working with files and directories, executing shell commands, etc
<br><br>
The environ attribute is a dictionary-like object that contains the environment variables of the current operating system session
<br><br>
By accessing os.environ, you can retrieve and manipulate environment variables within your Python program. For example, you can retrieve the value of a specific environment variable using the syntax os.environ['VARIABLE_NAME'], where "VARIABLE_NAME" is the name of the environment variable you want to access.
<font>

In [1]:
import os
os.environ["OPENAI_API_KEY"] = ""

<font color='green'>
LangChain has built a Wrapper around OpenAI APIs, using which we can get access to all the services OpenAI provides.
<br>
The code snippet below imports a specific class called 'OpenAIEmbeddings'(Wrapper around OpenAI large language models) from the 'embeddings' module of the 'langchain' library.

<font>

In [2]:
#As Langchain team has been working aggresively on improving the tool, we can see a lot of changes happening every weeek,
#As a part of it, the below import has been depreciated
#from langchain.embeddings import OpenAIEmbeddings

#New import from langchain, which replaces the above
from langchain_openai import OpenAIEmbeddings

<font color='green'>
Initialize the OpenAIEmbeddings object
<font>

In [3]:
embeddings = OpenAIEmbeddings()

<font color='green'>
Let's read our input data and get its embedding representation, so that we use it up for our future tasks
<font>

In [4]:
#install the below if already not installed...
#!pip install pandas
#!pip install openpyxl

import pandas as pd
df = pd.read_excel('data.xlsx')
print(df)

         Words
0     Elephant
1         Lion
2        Tiger
3          Dog
4      Cricket
5      Footbal
6       Tennis
7   Basketball
8        Apple
9       Orange
10      Banana

<font color='green'>
    We can use "apply" to apply the get_embedding function to each row in the dataframe because our words are stored in a pandas dataframe. In order to save time and to save the calculated word embeddings in a new csv file called "word_embeddings.csv" rather than calling OpenAI once more to carry out these computations.
    <font>

In [5]:
df['embedding'] = df['Words'].apply(lambda x: embeddings.embed_query(x))
df.to_csv('word_embeddings.csv')

<font color='green'>
    Let's load the existing file, which contains the embeddings, so that we can save chargers by not hitting the API repeatedly
    <font>

In [6]:
new_df = pd.read_csv('word_embeddings.csv')
print(new_df)

    Unnamed: 0       Words                                          embedding
0            0    Elephant  [-0.018833934305000737, -0.008583207179144979,...
1            1        Lion  [-0.00147486492726733, -0.009976742060418075, ...
2            2       Tiger  [-0.013450920651544518, -0.009607800332342858,...
3            3         Dog  [-0.0008754995197025781, -0.015118821744363069...
4            4     Cricket  [0.0038929415221177544, -0.00723387463282558, ...
5            5     Footbal  [-0.011474513216262, -0.008092077284991004, 0....
6            6      Tennis  [-0.023023091202830612, 0.0015749745034138822,...
7            7  Basketball  [-0.012938675909892712, -0.013289385926366725,...
8            8       Apple  [0.013417293640589776, -0.005096784561748968, ...
9            9      Orange  [0.020728384163457052, -0.029429515310106256, ...
10          10      Banana  [-0.013066130403109374, -0.020126866162426614,...

<font color='green'>
Let's get the embeddings for our text
<font>

In [7]:
our_Text = "Cat"

In [8]:
text_embedding = embeddings.embed_query(our_Text)

In [9]:
print (f"Our embedding is {text_embedding}")

Our embedding is [-0.008235762179349014, -0.007498231508971353, -0.009963496931232996, -0.024789235476854268, -0.012790698998500619, 0.006682167059785173, -0.001548473660134367, -0.03785992544118277, -0.014409170050845979, -0.02622332327952858, 0.017181739802682987, 0.04624592299550619, 0.00358521997234709, 0.004223730560537031, -0.032342099766917536, -0.004657371595676728, 0.03941693292677749, 0.0052139341763820495, 0.00785333876530253, -0.01558375691636204, -0.023751229865576044, 0.005340270416285077, 0.014900857164431085, -0.012114629566567075, -0.006774358684620695, 0.0043500668004400585, 0.012387789281074936, -0.013343847816191145, 0.005633917365494744, 0.0009202064564646778, 0.009861062620369176, -0.01660810468161326, -0.017741718009048318, -0.03930767015856147, -0.02944660660686969, -0.0003254440783355343, 0.011452217049337925, -0.007354822728703921, 0.020732815159962573, -0.01390382509123387, 0.009478639206322694, 0.009799601847586364, -0.01341896643500096, 0.011937075705570835, -0.0023560017227230194, 0.010489329125546912, -0.021784479548590405, -0.007491402585957852, -0.006187065251862664, 0.012483395134586557, 0.006617292058326261, 0.0068460630747544104, -0.005688549215264055, 0.014067720174880501, -0.005019308240682708, 0.0056509899058591485, 0.008625014982070302, -0.012100971720540072, 0.013473598750431574, -0.000666680186658947, 0.012326327576969517, 0.004247632023914936, -0.006402178887925114, 0.02507605303738913, 0.007928458315434952, -0.005111499399856927, -0.004756392143525751, -3.644573678663988e-06, -0.0039983737727849805, 0.00395057084602917, 0.04173879096575561, 0.016594447766908865, 0.021565952149513158, -0.00914401871903202, -0.006989471855021842, -0.0003580952011878978, -0.018219747276606423, 0.011493191518741537, 0.0008809397998910695, -0.01110393871602025, 0.03575659293863668, -0.03302499765620328, -0.013268728266058724, 0.009253282418570643, 0.021825454017994017, 0.007423112890161538, -0.004930531310184588, 0.009806430304938562, -0.011998536478353647, 0.009253282418570643, 0.015269622732450567, 0.024092678810218916, -0.013958456475341878, 0.04244900640974057, -0.011540994445497348, 0.020309417276512476, -0.01324141257400472, 0.022180561739986497, -0.0014545750373761211, -0.05769131158749192, 0.0046095686689209174, 0.00584220161288239, -0.04834925177276186, -0.009403519656190271, -0.0029774400033792075, -0.0015868866431236247, 0.016894922242148124, 0.003796918681241487, 0.020760130852016577, -0.005804641837816179, -0.0027435469454449553, 0.05381244606291907, 0.020814764098769797, -0.030320718065823888, 0.007354822728703921, -0.003619365053075899, 0.00030474371627595484, -0.028517863763807483, 0.004401284421533271, -0.01973578215544275, 0.01924409597318025, 0.01390382509123387, 0.03843356056225249, 0.004408113344546772, 0.022781512553110225, 0.017605137686133084, -0.010079590019446423, 0.008024064168946571, -0.013637493834078206, 0.01600715386848953, 0.027753016935714518, 0.003650095439467305, 0.009178163799760828, 0.009362546118109267, -0.0030389007761620203, 0.026619405470924673, -0.04102857552177065, -0.0022621032163800997, -0.003223283560171761, -0.06692410490871555, -0.0026496484391020352, 0.01888898825118777, -0.020213811423000855, 0.017250029964140604, -0.0024516075762346405, 0.023805861249684052, 0.017345635817652225, 0.002455022037741391, 0.009157676565059022, 0.005446119887147601, 0.00913035994168241, -0.0010969066438765672, 0.03010219066674664, -0.01626665573697039, -0.004691516676405536, 0.03010219066674664, -0.0008459412202008992, 0.013453111515729768, 4.449514170529341e-05, -0.013917482937260871, 0.0014699402305718243, -0.004070078162918696, 0.01727734565619461, -0.011841469852059213, 0.0021425958994905733, 0.018506564837141287, 0.023081988890994696, 0.0030371936618239707, -0.017359294595001833, 0.00362960843759615, -0.02145668751865193, 0.018848013781784155, -0.008638672828097304, 0.013186781189896711, -0.010284459572496667, 0.0066753381367716715, -0.012339986354319125, -0.007737246142750406, -0.015884232322923904, -0.023327831982125947, -0.015720336307954667, 0.008713792378229725, 0.01546083443947381, 0.027165724899940395, -0.0037217998296010207, 0.007423112890161538, 0.0199406526398156, -0.01871143345886892, -0.004500304969382294, -0.00738896780943273, 0.00961521859791532, 0.025144343198846748, 0.02114255426606306, -0.024051704340815303, -0.6756876343682898, -0.027356936606963637, -0.01528328057847757, -0.007546034435727164, 0.014668671919326838, 0.020965001336389427, 0.0024157553811677826, 0.004377382958155366, 0.0013845778779957808, -0.00730019087893461, -0.01106979363529144, 0.006152920636795158, 0.0070270311644267495, -0.009772285224209754, -0.009458151971620886, -0.009089386403601405, -0.00878891099703954, -0.015815942161466288, -0.02065086808380056, 0.02099231702844343, 0.0052173488707194515, 0.004449087348289082, -0.004134953630038911, -0.012940937167442854, 0.006395349499250309, -0.009225966726516639, 0.0113292955037723, -0.02795788742008737, 0.02316393596715671, 0.021333765973086304, -0.014395512204818977, 0.02467997270863825, -0.00398130169808188, -0.018465590367737674, 0.048977522003230016, 0.017345635817652225, 0.002595016356502072, 0.022235193124094502, 0.008071867095702382, 0.03865208609868452, -0.018629486382706912, -0.018902645165892164, 0.018629486382706912, -0.0014033575326982343, -0.027425226768421254, -0.01610275972200115, 0.0008036868224973897, 0.0015561562567322185, 0.006350961266831902, -0.005364171879662982, 0.007580179516455972, -0.00838600034829125, 0.004886142612104877, -0.008351855267562441, 0.0060812162466614425, 0.008795739454391738, 0.024966790269173113, -0.017140767195924587, 0.0033086460291631304, 0.008549896363260487, -0.0060778015523240405, 0.00553489681764572, -0.004414942267560273, -0.019612860609877124, -0.013610178142024202, 0.0075392055127136625, -0.01752319060997107, 0.00035468071057731586, 0.025554082304947233, 0.01032543404190028, 0.006504613664450236, 0.002485752656963449, -0.03051192977284713, -0.0014545750373761211, 0.004459330965639985, 0.027520832621932875, 0.0049544327735624935, -0.010837608390187194, -0.00010728984130929553, -0.02024112897770007, -0.006477297506734928, -0.0026291614372308805, -0.025212633360304364, -0.010919556397671813, 0.018492906059791675, -0.013214096881950715, -0.023573675073257198, -0.0008450876048242116, 0.01592520679232752, 0.008802568843066542, 0.004858826920050872, 0.03144067261590933, -0.011349782738474107, 0.01537888643198919, -0.014928173787807695, 0.004674444136041132, -0.005835372224207586, 0.002507946773172653, 0.013985773098718488, -0.03422689928245074, -0.0011549530715679551, -0.006053900088946135, 0.008754765916310732, -0.0028067150653964686, 0.01651249882810164, 0.015037437487346319, -0.01432722204336136, 0.018014876792233573, 0.035483436018096635, -0.015515466754904424, 0.009669850913345934, -0.0077099304506964015, -0.01032543404190028, 0.00020262895092963842, 0.012660948995582797, -0.03021145343496266, 0.009703995994074744, 0.0045173770440853946, 0.01707247703446697, -0.017209055494736992, -0.01106979363529144, 0.023068330113645088, 0.012756554849094418, -0.004763221066539252, 0.007470915816917349, 0.00027508027634582944, -0.024461443446915792, 0.0013231168723823166, -0.004957847002238593, -0.008351855267562441, 0.006661680290744669, -0.01377407415699344, 0.008720620835581923, -0.01165708660238817, 0.004196414868483027, 0.006190479946200066, 0.02543116075938161, 0.012893134240687044, 0.017140767195924587, -0.0027845209491872648, -0.019804072316900366, 0.009464981360295692, 0.0029928051965749107, 0.006921182159225528, 0.019626519387226732, 0.0006871671885301017, -0.005995853544839422, -0.024802894254203876, 0.007730417219736905, 0.0001962267773968183, -0.013637493834078206, -0.009328401037380458, 0.02421560035578454, 0.01834266882217205, 0.03504638121994214, -0.02417462588638093, -0.0029245152679479454, -0.016485183136047635, -0.016853949635389723, -0.005995853544839422, 0.007266045798205801, 0.030484614080793126, -0.004302263873684248, -0.011807324771330405, -0.012626803914853988, -0.022522010684629366, 0.008686475754853115, 0.02865444408672272, -0.02955587123773092, -0.03384447586840426, 0.0002780679592680676, -0.02186642848739763, -0.00526173710313786, 0.010468842822167711, 0.0095332705904307, 0.004636884826636225, 0.013207267493275911, -0.030648510095762364, 0.004858826920050872, 0.009826917539640368, 0.02427023173989255, -0.005292467489529266, -0.010782976074756579, -0.0027520832156271574, -0.0011967806324792894, 0.014245274035876741, 0.04195731650218765, 0.020336734831211692, -0.01570667753060506, 0.016444208666644023, -0.013350676273543343, 0.003861794148361702, 0.0007955773891073629, 0.008686475754853115, -0.0024686801165990447, -0.019749440932792357, -0.0019735783086765354, 0.017058818257117362, 0.01610275972200115, 0.027111093515832387, -0.0031174340893092367, 0.00878891099703954, 0.0073753099634057285, -0.007580179516455972, 0.018766066705622145, -0.037368235533629834, -0.014504775904357598, -0.005910491308678704, 0.02698817010762155, 0.028627128394668716, -0.0016227388381904826, -0.003926669382651265, -0.01681297516598611, -0.010086419408121227, 0.013446282127054964, 0.020664524998504956, -0.00730019087893461, 0.0035510751244489337, -0.0024345350358702363, -0.0021494248225040744, -0.011288321034368687, -0.005183203789990643, -0.003093532625931332, 0.020623552391746555, 0.003773017217863582, 0.018042192484287577, 0.014682329765353839, 0.0370950786130898, 0.0021938132877531344, -0.025567741082296844, -0.026441850678605827, -0.0014801837315074017, 0.00561684482513034, 0.0075392055127136625, 0.002757205024302609, -0.0001443691339459944, 0.025198974582954753, -0.015611072608416045, 0.033817162038995464, 0.014736962080784455, -0.004346652571763959, 0.030948984571001623, 0.009424006890892078, -0.02141571491189353, 0.009198650103140029, -0.0008980122820478108, 0.022781512553110225, 0.017058818257117362, -0.0031225558979846887, 0.01354871736924139, -0.014163326028392122, 0.0034913214660041705, -0.018861672559133767, 0.01487354147237708, 0.004647127978325824, -0.016731026227178886, 0.021484005073351145, 0.01032543404190028, 0.019653835079280736, 0.02588187433488571, 0.017031502565063358, 0.007238730106151798, 0.0010038615782873462, -0.002313320604642661, 0.012360472657698325, 0.011923417859543832, 0.010687370221244958, -0.017714402316994313, 0.02325954182066833, -0.000178834196749777, -0.014846225780323076, -0.009983984165934802, 0.013364334119570345, -0.015187674724965948, 0.017454900448513454, 0.019667491993985133, -0.0012736067148731308, -0.0053846591143647884, 0.016048128337893142, -0.0007149099502069327, -0.018943619635295776, -0.04498938998515072, 0.021087922881955053, -0.001850656413864933, -0.0108785819282682, -0.004182756556794722, -0.02829933636473024, -0.01548815106285042, 0.0012189748651038194, 0.012360472657698325, 0.0015800577201101238, 0.016731026227178886, 0.01548815106285042, 0.01625299695962078, 0.010332262499252478, 0.002383317647607675, 0.03122214521683209, -0.018984594104699392, 0.009861062620369176, 0.00785333876530253, -0.003755944910329829, -0.025007762875931514, -0.006535344050841642, -0.022481036215225753, 0.013801389849047444, -0.009574245059834315, -0.014040404482826497, -0.022877118406621846, -0.0020623552391746554, -0.003154993631544796, -0.017250029964140604, 0.014313564197334358, -0.02186642848739763, -0.006989471855021842, -0.020568919144993335, -0.010161538026931042, -0.02784862278922614, -0.005975366775798918, 0.049032153387338025, -0.0006107678265131096, -0.012244380500807504, -0.008358684656237245, -0.03455469131238922, -0.014450144520249592, 0.09281964174624129, 0.005271980720488763, -0.01905288426615701, 0.013617007530699006, 0.0018438274908514321, -0.018588511913303296, -0.028927604732553187, -0.006948497851279533, 0.027206699369344008, 0.01118588672350487, -0.009731311686128747, 0.002210885595286887, 0.016143734191404763, -0.005855859458909392, 0.0005283931568593041, 0.015037437487346319, -0.021907401094156027, -0.002410633572492331, 0.009410349044865077, -0.014846225780323076, 0.00956741567115951, -0.0008199056892774434, 0.015351570739935186, 0.0028050079510584195, -0.006706068523163078, -0.007068005168169059, 0.0029330515381301475, 0.034063005130126715, 0.012251208958159702, -0.028135440349761003, 0.011021990708535632, 0.01651249882810164, -0.014286248505280354, -0.0037217998296010207, 0.007409454578473233, 0.0028493964163074795, -0.0031447502470245445, 0.01417698480574173, 0.02386049263379206, -0.022344457754955735, 0.018465590367737674, 0.025007762875931514, -0.016293971429024393, -0.013698955538183625, 0.007785049069506216, -0.0038583796868549513, -0.0036535099009740554, 0.018410958983629665, 0.016293971429024393, 0.0032608431024073203, 0.03638486316910484, 0.026086744819258562, -0.008447461121074062, 0.006682167059785173, -0.010974187781779821, -0.007047518399128556, 0.020350391745916088, -0.007231901183138297, -0.001708101307181852, -0.018602170690652908, -0.01671736931247449, -0.013862850621830257, 0.006105117710039348, 0.004701759828095136, -0.0020965000870728123, -0.024447786532211396, 0.004886142612104877, -0.02205764019442087, -0.027616438475444496, -0.00913035994168241, -0.013186781189896711, -0.023218567351264718, -0.024201943441080145, 0.010919556397671813, 0.007307019801948111, 0.011588797372253158, 0.01887532947383816, -0.022153246047932493, -0.002507946773172653, 0.023587333850606806, -0.014313564197334358, -0.024652655153939034, 0.001621885281021458, -0.03417226789834273, -0.022358114669660128, 0.0017388316935732584, -0.0018745578772428383, -0.009977154777259998, 0.00016720356355112438, 0.002046989813148301, 0.01793292971607156, -0.0030918255115932824, 0.036084384968575155, -0.006648022444717667, -0.006859720920781413, 0.007778220146492715, 0.00416568448209162, -0.007177268867707681, -0.0014340880355049664, -0.02980171432886217, 0.017441241671163846, -0.02437949637075378, -0.019039225488807397, -0.0009654485370904255, 0.005709035984304558, 0.0021118652802685155, 0.019121174427614625, 0.02840860099559147, -0.002065769700681406, -0.013890167245206867, 0.002115279741775266, -0.020719158245258176, -0.004735904908823944, -0.011158571031450865, 0.014095036798257111, 0.01752319060997107, -0.02422925913313415, 0.013234584116652522, 0.019257752887884644, -0.011568310137551352, -0.024789235476854268, -0.016130075414055155, 0.020336734831211692, 0.03122214521683209, -0.00717043994469418, -0.00494418915621159, 0.0005770496989918023, 0.006381691653223308, -0.007457257505229044, 0.00738896780943273, 0.005101255782506024, 0.009232795183868837, -0.015160359032911944, -0.04206658299569409, -0.02222153620939011, -0.011759521844574594, -0.01188244339014022, 0.010776146686081773, -0.0014690865569874738, -0.015447176593446807, -0.03859745471457651, 0.004169098710767719, 0.004759806372201849, -0.024352180678699775, -0.021893744179451634, -0.04386943729771049, -0.031276778463585314, -0.0016048127406570536, 0.00398130169808188, 0.021634242310970775, -0.011342953349799302, 0.00913035994168241, -0.00935571672943446, -0.01241510497312894, -0.01636226159048201, -0.027274987668156413, -0.015078411025427325, -0.00045754238210227605, 0.031003617817754844, 0.020527946538234934, -0.0022074711337801366, 0.0005394902731715691, 0.015474492285500812, -0.003834478223477046, -0.00761432459718478, 0.00988837831242318, 0.010038616481365416, 0.008993780550089784, -0.03247868008983277, 0.010291288961171471, 0.013050200866981478, -0.0008006991395751516, -0.002137474090815122, -0.0016073736449947794, -0.01924409597318025, 0.01737295150970623, 0.007272875186880606, -0.015160359032911944, -4.713604156176275e-05, -0.003974472309407075, 0.013678468303481819, -0.0009449615934269336, 0.014859883626350079, 0.014163326028392122, 0.001641518609308262, -0.006050485860270036, 0.010762488840054773, 0.0012360472890528976, -0.01201219432438065, 0.004363725112128364, 0.01842461589833406, -0.01050298790289652, 0.00697581400899484, -0.02865444408672272, 0.010113735100175231, -0.03611170252327437, -0.011820982617357407, -0.0007605788094171927, -0.0020674768150194555, -0.012339986354319125, 0.0020965000870728123, 0.037450184472437066, 0.002666720746635788, 0.008754765916310732, -0.0013786025121513045, -0.004261290335603241, 0.0001845961587500814, -0.01458672391184222, 0.005138815557572235, -0.016403236059885622, -0.011001503473833824, -0.016703710535124882, -0.05687183337529095, -0.03206893912108707, -0.005705621755628459, 0.0011148327414099962, -0.006962155697306535, 0.010851266236214196, -0.01570667753060506, -0.008406487582993056, -0.014655014073299836, 0.00048528514377910707, 0.028791024409637954, -0.02411999450227292, 0.030648510095762364, 0.030293402373769884, -0.015693020615900662, -0.010598593756408141, 0.011390756276555112, -0.014750619926811457, -0.04662834640955268, 0.006374862730209807, 0.0013657981068780013, -0.00883671392379535, 0.01602081264583914, -0.00021212551658274053, 0.0066685092137581704, -0.014258931881903742, -0.02974708294475416, 0.0240243886487613, 0.023122961497753097, -0.006282671105374284, -0.02595016449634333, 0.011090280869993249, -0.013255070420031722, 0.017810008170505934, -0.0122375511121327, -0.007068005168169059, -0.0363302280597064, -0.006391935270574211, -0.01923043719583064, 0.012442420665182944, -0.021115238574009057, 0.014709645457407843, 0.00326596467825212, -0.0032881590272919757, 0.016444208666644023, 0.012223893266105698, -0.005097841553829925, -0.016908581019497732, -0.02717938181464479, 0.015269622732450567, -0.011691231683116978, 0.030839721802785606, 0.017181739802682987, 0.0017430998286643595, -0.01469598761138084, -0.001377748838566954, -0.019216780281126247, 0.03206893912108707, -0.000977399326987041, -0.009451322582946082, 0.009478639206322694, -0.01592520679232752, 0.01039372327203529, -0.02099231702844343, -0.01656713207485486, 0.004889557306442279, -0.01942164890285388, -0.036903866906066556, 0.01626665573697039, 0.01052347420627572, -0.013036543020954475, 0.0018933376483606177, -0.014914515010458087, -0.015693020615900662, -0.00507394009045202, -0.0181377983377992, -0.017714402316994313, -0.009902036158450183, -0.012162432493322885, -0.002472094578105795, 0.016881265327443728, 0.002144303013828623, 0.010024958635338414, -0.006016340779541228, -0.001183976227205986, 0.03422689928245074, -0.011568310137551352, 0.02745254246047526, -0.024611682547180633, 0.010612251602435143, -0.021484005073351145, -0.007723588296723404, 0.0055622129753610285, 0.006999715472372745, 0.011609283675632359, -0.01828803743806404, -0.00791480046940795, 0.00044516481362114817, -0.005193447407341546, 0.0034025445355060505, -0.011616113064307163, 0.008317710186833633, 0.0013709199155534529, 0.0049544327735624935, 0.011814154160005209, -0.011773179690601597, -0.015064753179400323, 0.017454900448513454, -0.008829884535120546, 0.006801674842336002, 0.0028937846487258876, -0.005289053260853167, 0.007156782098667179, -0.019080199958211013, 0.020527946538234934, 0.01574765200000867, -0.008242591568023818, -0.014272590659253351, -0.014736962080784455, 0.014286248505280354, -0.00015407910344326838, -0.03646680838262164, -0.022672247922248995, -0.035483436018096635, -0.01701784378771375, 0.021224503204870286, -0.015419860901392803, -0.0077167593737099026, 0.005627088442481243, 0.008625014982070302, -0.005435876269796697, 0.007368481040392227, -0.016649079151016873, -0.023956098487303682, -0.007846510307950331, 0.007907971080733144, -0.02799886188949098, -0.007935286772787148, -0.022986383037483075, 0.023232226128614326, 0.009540099979105507, -0.037204341381305815, -0.01157513859490355, 0.008652330674124306, -0.026796958400598307, 0.0014229908609850385, -0.002079427546708408, 0.009772285224209754, 0.0024959960414837005, -0.0167720006965825, 0.015733995085304278, 0.0060778015523240405, -0.006610462669651457, 0.014559408219788215, -0.021033291497847044, -0.009799601847586364, 0.012128287412594077, 0.005050038627074115, 0.024393155148103387, -0.012524368672667563, -0.0122

<font color='green'>
    We can determine how similar a word is to other words in our dataframe after we have a vector representing that word.
    <br>
By computing the cosine similarity of the word vector for our search term to each word embedding in our dataframe.
    <font>

In [10]:
# embeddings_utils class has been remove by OpenAi from 1.1.version, so we will use the code to find the cosine similarity :)

#from openai.embeddings_utils import cosine_similarity


import numpy as np
#Creating a function which will help us with finding the cosine_similarity score
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

df["similarity score"] = df['embedding'].apply(lambda x: cosine_similarity(x, text_embedding))

df

,Words,embedding,similarity score
0,Elephant,"[-0.018833934305000737, -0.008583207179144979,...",0.819499
1,Lion,"[-0.00147486492726733, -0.009976742060418075, ...",0.839910
2,Tiger,"[-0.013450920651544518, -0.009607800332342858,...",0.846864
3,Dog,"[-0.0008754995197025781, -0.015118821744363069...",0.878325
4,Cricket,"[0.0038929415221177544, -0.00723387463282558, ...",0.795419
5,Footbal,"[-0.011474513216262, -0.008092077284991004, 0....",0.779953
6,Tennis,"[-0.023023091202830612, 0.0015749745034138822,...",0.784875
7,Basketball,"[-0.012938675909892712, -0.013289385926366725,...",0.784836
8,Apple,"[0.013417293640589776, -0.005096784561748968, ...",0.830426
9,Orange,"[0.020728384163457052, -0.029429515310106256, ...",0.811837
10,Banana,"[-0.013066130403109374, -0.020126866162426614,...",0.806726

<font color='green'>
    Sorting by similarity values in dataframe reveals Dog, Tiger, and Lion are closest to searched term, such as Cat.
    <font>

In [11]:
df.sort_values("similarity score", ascending=False).head(10)

,Words,embedding,similarity score
3,Dog,"[-0.0008754995197025781, -0.015118821744363069...",0.878325
2,Tiger,"[-0.013450920651544518, -0.009607800332342858,...",0.846864
1,Lion,"[-0.00147486492726733, -0.009976742060418075, ...",0.839910
8,Apple,"[0.013417293640589776, -0.005096784561748968, ...",0.830426
0,Elephant,"[-0.018833934305000737, -0.008583207179144979,...",0.819499
9,Orange,"[0.020728384163457052, -0.029429515310106256, ...",0.811837
10,Banana,"[-0.013066130403109374, -0.020126866162426614,...",0.806726
4,Cricket,"[0.0038929415221177544, -0.00723387463282558, ...",0.795419
6,Tennis,"[-0.023023091202830612, 0.0015749745034138822,...",0.784875
7,Basketball,"[-0.012938675909892712, -0.013289385926366725,...",0.784836